apiVersion: v1
kind: ConfigMap
metadata:
  name: workerenviarmensagem-configmap
  namespace: teleapp-wokerenviarmensagem
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "ConnectionStrings": {
        "MongoDB": "MONGO_CONNECTION"
      },
      "KafkaConfiguration": {
        "Broker": "KAFKA_BROKER",
        "ConsumerGroup": "teleappbot-consumer-texto",
        "TopicoMensagemTexto": "teleappbot-mensagem-texto",
        "TopicoMensagemMidia": "teleappbot-mensagem-midia"
      }
    }