apiVersion: v1
kind: ConfigMap
metadata:
  name: teleappapi-configmap
  namespace: teleapp-api
data:
  appsettings.json: |-
    {
      "Kestrel": {
        "Endpoints": {
          "Http": {
            "Url": "http://0.0.0.0:2712"
          },
          "Https": {
            "Url": "https://0.0.0.0:2711"
          }
        },
        "EndpointDefaults": {
          "Url": "https://0.0.0.0:5001",
          "Protocols": "Http1"
        }
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "MongoDB": "{MONGO_CONNECTION}"
      },
      "KafkaConfiguration": {
        "Broker": "{KAFKA_BROKER}",
        "ConsumerGroup": null,
        "TopicoMensagemTexto": "teleappbot-mensagem-texto",
        "TopicoMensagemMidia": "teleappbot-mensagem-midia"
      }
    }
