apiVersion: apps/v1
kind: Deployment
metadata:
  name: teleappapi-deployment
  namespace: teleapp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teleappapi
  template:
    metadata:
      labels:
        app: teleappapi
    spec:
      containers:
      - name: teleappapi
        image: matheusaoc/teleappbot-api:v1.0.6
        imagePullPolicy: Always
        env:
        - name: KAFKA_USER
          value: KAFKA_USER
        - name: KAFKA_PASSWORD
          value: KAFKA_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2711
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          configMap:
            name: teleappapi-configmap
