apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerenviarmidia-deployment
  namespace: teleapp-wokerenviarmidia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workerenviarmidia
  template:
    metadata:
      labels:
        app: workerenviarmidia
    spec:
      containers:
      - name: workerenviarmidia
        image: matheusaoc/teleappbot-workerenviarmidia:v1.0.1
        imagePullPolicy: Always
        env:
        - name: KAFKA_USER
          value: KAFKA_USER
        - name: KAFKA_PASSWORD
          value: KAFKA_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          configMap:
            name: workerenviarmidia-configmap
