---
version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: usrTeleAppBot
      MONGO_INITDB_ROOT_PASSWORD: pwdTeleAppBot
      MONGO_INITDB_DATABASE: teleAppBot
    volumes:
       - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro